### ISSUE TITLE
No Sierra Support (10.12)

### ISSUE THREAD

**Issue by yagmot** [jacobsalmela/NCutil#17]
Using 10.12.6
Example:

```
$ ./NCutil.py -l
Traceback (most recent call last):
  File "./NCutil.py", line 605, in <module>
    main()
  File "./NCutil.py", line 572, in main
    list_clients()
  File "./NCutil.py", line 100, in list_clients
    curs.execute("select bundleid from app_info")
AttributeError: 'NoneType' object has no attribute 'execute'
```

**Comment by gandalfsaxe** [comment]
Yes please! I need this amazing app so badly 😊 

Doesn't work on latest macOS 10.14 Mojave beta. Should I make a separate issue or is this considered the "support latest macOS" issue?

**Comment by shockey** [comment]
I poked around in the Sierra NotificationCenter database, and it's not clear that notification preferences are stored there any longer — curious if anyone has insights on where the settings have gone!

**Comment by kylesm** [comment]
> Doesn't work on latest macOS 10.14 Mojave beta. Should I make a separate issue or is this considered the "support latest macOS" issue?

It seems like Mojave's NC database path and format are different from 10.10-10.13 so a minor tweak to PR #18 wouldn't do it – IMO a separate issue would be good.
